### ISSUE TITLE
Delimiters doesn't appear to be working

### ISSUE THREAD

**Issue by jamesrichards** [m59peacemaker/js-qs#3]
Hello,

Firstly - thanks for producing this :smiley:

Unless I'm missing something - the delimiters option doesn't appear to be working for me. 

I've just clean installed the module via npm and required it within a module.

The docs suggest that the delimiter option should work like this:

```
stringify({ foo: ['a', 'b', 'c'] }, { delimiter: ';' })
// => 'foo=a;b;c'
```

But here's what I get back when running the same thing:

```
stringify({ foo: ['a', 'b', 'c'] }, { delimiter: ';' })
// => 'foo=a&foo=b&foo=c'
```

I could be blindly missing something - but I can't see anything obvious that I'm missing right now. It is 2am here though :sweat_smile:

Thanks

**Comment by m59peacemaker** [comment]
Close! This should be what you're looking for:

```js
stringify({ foo: ['a', 'b', 'c'] }, { arrayFormat: { delimiter: ';' } })
```

That's how 2am rolls. xD

**Comment by m59peacemaker** [comment]
Ah. I see there's inconsistency in my docs! It's right in one place, wrong in the other. It's good to check the tests since they definitely know what works. Sorry about that! [Fixed](https://github.com/m59peacemaker/js-qs/commit/d2cd1260ed85626c0420d6b3910f40ff07b3f770#diff-04c6e90faac2675aa89e2176d2eec7d8R85).

**Comment by jamesrichards** [comment]
Ah - well spotted! Thanks for the quick turnaround. :thumbsup:
